me: echi_recipe
channels:
  - conda-forge
  - pytorch
dependencies:
  - cython
  - hydra-core
  - hydra-submitit-launcher
  - librosa
  - matplotlib
  - numpy==1.26.4
  - omegaconf
  - onnxruntime
  - pip
  - tqdm
  - wandb
  - sentencepiece  # from conda-forge (prebuilt)
  - pip:
      - auraloss
      - torch-stoi

